In [90]:
import cv2
import pytesseract
import matplotlib.pyplot as plt
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract'
img = cv2.imread(r'C:\\Users\\Naeem\\OCR\\Materials\\zampal.png')
#img = cv2.resize(imS, (900,900))  
cv2.imshow("Image", img)
text = pytesseract.image_to_string(img)
print(text)
cv2.waitKey(0)
cv2.destroyAllWindows()

10,200.00

mS

1,500.00

10,200.00




In [91]:
# C:\Program Files\Tesseract-OCR
    
import cv2
import pytesseract
import matplotlib.pyplot as plt
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract'

cv2.imshow("Image", img)
text = pytesseract.image_to_string(img)
print(text)
cv2.waitKey(0)
cv2.destroyAllWindows()

10,200.00

mS

1,500.00

10,200.00




In [92]:
from PIL import Image
import pytesseract
import numpy as np

In [93]:
filename = 'C:\\Users\\Naeem\\OCR\\Materials\\zampal.png'
img2 = np.array(Image.open(filename))
text = pytesseract.image_to_string(img2)
#print(text)

In [94]:
from pytesseract import Output
import pytesseract
import cv2


In [95]:

image = cv2.imread(filename)

In [96]:
results = pytesseract.image_to_data(image, output_type=Output.DICT)

In [97]:

image = cv2.imread(filename)

In [98]:
results = pytesseract.image_to_data(image, output_type=Output.DICT)

In [99]:
print(results)

{'level': [1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5], 'page_num': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'block_num': [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20], 'par_num': [0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 

In [100]:
for i in range(0, len(results["text"])):
    x = results["left"][i]
    y = results["top"][i]
    
    w = results['width'][i]
    h = results['height'][i]
    text = results['text'][i]
    conf = int(float(results['conf'][i]))
    if conf>70 :
        text = "".join([c if ord(c) < 128 else "" for c in text]).strip()
        cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.putText(image, text, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 200), 2)

In [ ]:
#imS = cv2.resize(image, (900, 900))  
cv2.imshow("",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [88]:
print(image)

[[[251 248 248]
  [253 250 250]
  [253 255 255]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[254 253 253]
  [254 253 253]
  [255 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[255 255 255]
  [255 254 254]
  [255 255 255]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[239 236 239]
  [210 208 209]
  [244 244 244]
  ...
  [251 248 248]
  [253 249 249]
  [253 253 253]]

 [[250 250 250]
  [235 235 233]
  [249 249 249]
  ...
  [254 251 252]
  [254 253 253]
  [255 254 254]]

 [[249 249 249]
  [249 248 248]
  [253 250 250]
  ...
  [255 253 253]
  [251 251 251]
  [253 250 250]]]


In [89]:
crop=image[100:1200,0:1500]

In [ ]:
crop.shape

(380, 640, 3)

In [ ]:
crop.size

729600

In [ ]:
cv2.imshow("",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()